Hey! 🙋🏾‍♂️ I'm Tanishq. Moonrise is my personal website. I mostly use it as a space to express myself.

I love thinking about rich text editors, extensible programming languages, and just expressive, fun, robust interfaces to software.

I recently graduated from Carnegie Mellon University majoring in physics and computer science, and I'm currently looking for my next opportunity.

---

My newest project is Gem, a performant and simple plaintext editor:
[✳️ Gem](https://gem.tanishqkancharla.dev)

---

I've started to write a blog. I talk mostly about designing new interfaces, making computers better, and my personal life.
[🌙 Blog Posts](/blog)

---

I also keep a separate table for thoughts: just whims, half-baked ideas, and streams of consciousness.
[🧠 Thoughts](/thoughts)

---

In my free time, I play basketball and video games, but I also like to work on projects.
[🛠 Projects](https://thoughts-tk.notion.site/thoughts-tk/e6a05b5609bf4cf8a3d66c967302e483?v=4deb8a7b7be14df4a4e109cdfa7f8fb9)

---

I don't have much job experience yet but if you're curious, here is my resume:
[📋 Experience](https://read.cv/tk)

---

If you have any feedback or questions about me or my website, please let me know! I'm always looking to iterate.
If you want to get in touch, my email is [tanishqkancharla3@gmail.com](mailto:tanishqkancharla3@gmail.com) and my twitter is [@moonriseTK](https://twitter.com/moonriseTK).
Also, here's my [Github profile](https://github.com) and [the source of this website](https://github.com/tanishqkancharla/tanishqkancharla.dev).
