Hey! 🙋🏾‍♂️ I'm Tanishq, a 23 yo full-stack developer. This is my personal website. I mostly use it as a space to express myself.

I love thinking about rich text editors, extensible programming environments, functional programming, and just expressive, fun, robust interfaces to software.

I'm currently looking for my next opportunity. Previously I was [working with Chet Corcos](/blog/what-i-learned). Here's how I'm evaluating companies:

1. Do I have a lot to learn from the team/will this stretch my boundaries?
2. Do I think this product will be successful?
3. Ideally in-person, with at least 5 people (on East Coast, but eh that’s flexible).
4. Does working on this product and with this team sound fun?
5. Compensation

If you think I would be a good fit, please reach out!

---

[🧠 What am I thinking about this year?](/thinking)
What am I thinking about/working on this year (2023)?

---

[🌙 Blog Posts](/blog)
I've started to write a blog. I talk mostly about designing new interfaces, making computers better, and my personal life.

---

[💭 Thoughts](/thoughts)
I also keep a separate table for thoughts: just whims, half-baked ideas, and streams of consciousness.

---

[🛠 Projects](/projects)
In my free time, I play basketball and video games, but I also like to work on projects.

---

[📋 Resume](https://read.cv/tk)

---

If you have any feedback or questions about me or my website, please let me know! I'm always looking to iterate.
If you want to get in touch, my email is [tanishqkancharla3@gmail.com](mailto:tanishqkancharla3@gmail.com) and my twitter is [@moonriseTK](https://twitter.com/moonriseTK).
Also, here's my [Github profile](https://github.com/tanishqkancharla) and [the source of this website](https://github.com/tanishqkancharla/tanishqkancharla.dev).
